spring:
  application:
    name: MyNotes

  datasource:
    url: jdbc:postgresql://localhost:5432/mynewdb
    username: myuser
    password: 11111
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  port: 8080